package com.workdiary.app.data.storage

/**
 * Centralised namespace for all SharedPreferences key strings used throughout WorkDiary.
 *
 * Mirrors the iOS `KeyGen` struct. Profile-scoped keys are generated via functions that
 * accept a profile identifier (e.g. `"User1"`, `"User2"`), ensuring keys are never
 * accidentally shared between profiles. Global keys are exposed as plain constants.
 *
 * ### Profile values in use
 * - [PROFILE_USER1] — `"User1"` (default)
 * - [PROFILE_USER2] — `"User2"`
 *
 * ### Usage example
 * ```kotlin
 * val activeProfile = prefs.getString(PrefsKeys.ACTIVE_PROFILE, PrefsKeys.PROFILE_USER1)!!
 * val notesKey = PrefsKeys.notes(activeProfile)       // "dayNotesData_User1"
 * val holidaysKey = PrefsKeys.holidays(activeProfile) // "bookedHolidaysData_User1"
 * ```
 */
object PrefsKeys {

    // ─────────────────────────────────────────────────────────────────────────
    // Profile identifiers
    // ─────────────────────────────────────────────────────────────────────────

    /** Default active profile identifier. */
    const val PROFILE_USER1 = "User1"

    /** Secondary profile identifier. */
    const val PROFILE_USER2 = "User2"

    // ─────────────────────────────────────────────────────────────────────────
    // Private key-name constants (used by the generator functions below)
    // ─────────────────────────────────────────────────────────────────────────

    private const val KEY_DAY_NOTES_DATA      = "dayNotesData"
    private const val KEY_BOOKED_HOLIDAYS     = "bookedHolidaysData"
    private const val KEY_ANNUAL_ALLOWANCE    = "annualAllowance"
    private const val KEY_HOURLY_ALLOWANCE    = "hourlyAllowance"
    private const val KEY_IS_HOURS_MODE       = "isHoursMode"
    private const val KEY_CARRIED_OVER        = "carriedOverAllowance"

    // ─────────────────────────────────────────────────────────────────────────
    // Profile-scoped key generators  (matches KeyGen.swift 1-to-1)
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Key for the JSON-encoded map of day notes for [profile].
     *
     * Pattern: `dayNotesData_{profile}`
     */
    fun notes(profile: String): String = "${KEY_DAY_NOTES_DATA}_$profile"

    /**
     * Key for the JSON-encoded list of booked [Holiday] objects for [profile].
     *
     * Pattern: `bookedHolidaysData_{profile}`
     */
    fun holidays(profile: String): String = "${KEY_BOOKED_HOLIDAYS}_$profile"

    /**
     * Key for the annual leave *days* allowance for [profile].
     *
     * Pattern: `annualAllowance_{profile}`
     */
    fun annual(profile: String): String = "${KEY_ANNUAL_ALLOWANCE}_$profile"

    /**
     * Key for the annual leave *hours* allowance for [profile].
     *
     * Pattern: `hourlyAllowance_{profile}`
     */
    fun hourly(profile: String): String = "${KEY_HOURLY_ALLOWANCE}_$profile"

    /**
     * Key for the boolean flag indicating whether [profile] tracks leave in hours
     * (as opposed to days).
     *
     * Pattern: `isHoursMode_{profile}`
     */
    fun isHours(profile: String): String = "${KEY_IS_HOURS_MODE}_$profile"

    /**
     * Key for the carried-over allowance (days or hours) for [profile].
     *
     * Pattern: `carriedOverAllowance_{profile}`
     *
     * > **Note:** The iOS app contains a bug where SettingsView writes to a
     * > non-profile-scoped key (`carriedOverAllowance`), while BalanceView reads the
     * > profile-scoped version. Both are retained here for compatibility.
     */
    fun carriedOver(profile: String): String = "${KEY_CARRIED_OVER}_$profile"

    // ─────────────────────────────────────────────────────────────────────────
    // Global (non-profile-scoped) keys
    // ─────────────────────────────────────────────────────────────────────────

    /** One-time onboarding completion gate. Default: `false`. */
    const val HAS_COMPLETED_SETUP = "hasCompletedSetup"

    /**
     * The currently-active profile identifier (`"User1"` or `"User2"`).
     * Default: [PROFILE_USER1].
     */
    const val ACTIVE_PROFILE = "activeProfile"

    /** Display name for Profile 1. Default: `"Profile 1"`. */
    const val PROFILE_NAME_USER1 = "profileName_User1"

    /** Display name for Profile 2. Default: `"Profile 2"`. */
    const val PROFILE_NAME_USER2 = "profileName_User2"

    /** Global dark/light mode toggle. Default: `true` (dark). */
    const val IS_DARK_MODE = "isDarkMode"

    /** Whether the calendar week starts on Monday. Default: `true`. */
    const val START_ON_MONDAY = "startOnMonday"

    /**
     * Non-profile-scoped carried-over allowance.
     *
     * > **Bug note (from iOS):** SettingsView uses this global key while BalanceView uses
     * > the per-profile key generated by [carriedOver]. Retained here to allow a
     * > clean migration in the Android app.
     */
    const val CARRIED_OVER_ALLOWANCE_GLOBAL = "carriedOverAllowance"

    /** Whether daily reminder notifications are enabled. Default: `false`. */
    const val NOTIFICATIONS_ENABLED = "notificationsEnabled"

    /**
     * Daily reminder time stored as epoch-seconds (Long).
     * Default: `32400` (09:00 UTC).
     */
    const val NOTIFICATION_TIME = "notificationTime"

    /**
     * JSON-encoded list of user-defined custom special day overrides.
     * Read by the UK bank holiday calculator before falling back to the built-in logic.
     */
    const val SAVED_SPECIAL_DAYS_DATA = "savedSpecialDaysData"

    /**
     * Hardcoded (non-profile-scoped) day notes key used by the iOS Siri intents layer.
     *
     * > **Bug note (from iOS):** `DutyIntents.swift` uses this literal key instead of
     * > `KeyGen.notes(activeProfile)`, meaning it always reads User1's notes. Retained
     * > for parity; fix when porting the App Actions / widget layer.
     */
    const val DAY_NOTES_DATA_GLOBAL = "dayNotesData"
}
